### ISSUE TITLE
When used in a Rails system test, fails with "Not Implemented" error

### ISSUE THREAD

**Issue by jschoolcraft** [codeplant/simple-navigation#214]
Using some system specs and when I test against a page that uses render_navigation I get the error below.

```
  1) Admin when logged in is allowed to see the schools index
     Failure/Error: = render_navigation level: 1

     ActionView::Template::Error:
       Not Implemented



     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:26:in `instance_eval'
     # (eval):17:in `block (2 levels) in eval_config'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:84:in `items'
     # (eval):15:in `block in eval_config'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:31:in `run'
     # (eval):14:in `eval_config'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:26:in `instance_eval'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:26:in `eval_config'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/helpers.rb:31:in `load_config'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/helpers.rb:177:in `active_navigation_item_container'
     # /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/helpers.rb:87:in `render_navigation'
     # ./app/views/layouts/admin.html.slim:13:in `_app_views_layouts_admin_html_slim__4509361552262004149_47375776225600'
     # /usr/local/bundle/gems/apartment-2.1.0/lib/apartment/elevators/generic.rb:23:in `call'
     # /usr/local/bundle/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
     # /usr/local/bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
     # /usr/local/bundle/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/etag.rb:25:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/conditional_get.rb:25:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/head.rb:12:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:232:in `context'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/session/abstract/id.rb:226:in `call'
     # /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
     # /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
     # /usr/local/bundle/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/method_override.rb:22:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/runtime.rb:22:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/sendfile.rb:111:in `call'
     # /usr/local/bundle/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/urlmap.rb:68:in `block in call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/urlmap.rb:53:in `each'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/urlmap.rb:53:in `call'
     # /usr/local/bundle/gems/rack-2.0.4/lib/rack/builder.rb:153:in `call'
     # /usr/local/bundle/gems/rack-test-0.8.2/lib/rack/mock_session.rb:29:in `request'
     # /usr/local/bundle/gems/rack-test-0.8.2/lib/rack/test.rb:251:in `process_request'
     # /usr/local/bundle/gems/rack-test-0.8.2/lib/rack/test.rb:129:in `custom_request'
     # /usr/local/bundle/gems/rack-test-0.8.2/lib/rack/test.rb:58:in `get'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:69:in `process'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:41:in `process_and_follow_redirects'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/rack_test/browser.rb:22:in `visit'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/rack_test/driver.rb:44:in `visit'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/session.rb:274:in `visit'
     # /usr/local/bundle/gems/capybara-2.17.0/lib/capybara/dsl.rb:50:in `block (2 levels) in <module:DSL>'
     # ./spec/system/admin_system_spec.rb:24:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # RuntimeError:
     #   Not Implemented
     #   /usr/local/bundle/gems/simple-navigation-4.0.5/lib/simple_navigation/configuration.rb:26:in `instance_eval'

```

I've searched and didn't find anything interesting other than:

```
    SimpleNavigation.set_env(RailsApp::Application.root, 'test')
```

I tried setting that in my `rails_helper` but I'm still getting "Not Implemented".

**Comment by jschoolcraft** [comment]
User error, errrr.
