### ISSUE TITLE
Support for Rails 5

### ISSUE THREAD

**Issue by utkarsh2102** [codeplant/simple-navigation#216]
Tests are failing with Rails 5. Please enable the same.
Here are the logs:

```
Failures:

  1) SimpleNavigation::Renderer::List#render sets the right html classes on the rendered 'ul' tag
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:24:in `block (3 levels) in <module:Renderer>'

  2) SimpleNavigation::Renderer::List#render renders an 'ul' tag for the navigation
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:16:in `block (3 levels) in <module:Renderer>'

  3) SimpleNavigation::Renderer::List#render sets the right html id on the rendered 'ul' tag
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:20:in `block (3 levels) in <module:Renderer>'

  4) SimpleNavigation::Renderer::List#render when an item is selected renders the item's 'li' tag with its id and selected classes
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:53:in `block (4 levels) in <module:Renderer>'

  5) SimpleNavigation::Renderer::List#render when an item is selected renders the item's 'a' tag with the selected classes
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:57:in `block (4 levels) in <module:Renderer>'

  6) SimpleNavigation::Renderer::List#render when an item has no specified id renders the item's 'li' tag with the item's stingified key as id
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:29:in `block (4 levels) in <module:Renderer>'

  7) SimpleNavigation::Renderer::List#render when an item has a specified id renders the item's 'li' tag with the specified id
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:35:in `block (4 levels) in <module:Renderer>'

  8) SimpleNavigation::Renderer::List#render when the :ordered option is true sets the right html id on the rendered 'ol' tag
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:69:in `block (4 levels) in <module:Renderer>'

  9) SimpleNavigation::Renderer::List#render when the :ordered option is true sets the right html classes on the rendered 'ol' tag
     Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

     NameError:
       uninitialized constant SimpleNavigation::Renderer::HTML
     # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
     # ./spec/simple_navigation/renderer/list_spec.rb:73:in `block (4 levels) in <module:Renderer>'

  10) SimpleNavigation::Renderer::List#render when the :ordered option is true renders an 'ol' tag for the navigation
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/list_spec.rb:65:in `block (4 levels) in <module:Renderer>'

  11) SimpleNavigation::Renderer::List#render when no item is selected renders each item as 'a' tag without any selected class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/list_spec.rb:45:in `block (4 levels) in <module:Renderer>'

  12) SimpleNavigation::Renderer::List#render when no item is selected renders each item as 'li' tag without any selected class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/list_spec.rb:41:in `block (4 levels) in <module:Renderer>'

  13) SimpleNavigation::Renderer::List#render when a sub navigation item is selected renders the selected nested item's link as selected
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/list_spec.rb:90:in `block (4 levels) in <module:Renderer>'

  14) SimpleNavigation::Renderer::List#render when a sub navigation item is selected renders the parent items as selected
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/list_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/list_spec.rb:86:in `block (4 levels) in <module:Renderer>'

  15) SimpleNavigation::Renderer::Links#render sets the right html classes on the rendered 'div' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:24:in `block (3 levels) in <module:Renderer>'

  16) SimpleNavigation::Renderer::Links#render sets the right html id on the rendered 'div' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:20:in `block (3 levels) in <module:Renderer>'

  17) SimpleNavigation::Renderer::Links#render renders a 'div' tag for the navigation
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:16:in `block (3 levels) in <module:Renderer>'

  18) SimpleNavigation::Renderer::Links#render renders the 'a' tags with the corresponding item's :html_options
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:32:in `block (3 levels) in <module:Renderer>'

  19) SimpleNavigation::Renderer::Links#render renders an 'a' tag for each item
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:28:in `block (3 levels) in <module:Renderer>'

  20) SimpleNavigation::Renderer::Links#render when an item has no specified id uses a default id by stringifying the item's key
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:43:in `block (4 levels) in <module:Renderer>'

  21) SimpleNavigation::Renderer::Links#render when an item has a specified id renders the 'a' tags with the specified id
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:37:in `block (4 levels) in <module:Renderer>'

  22) SimpleNavigation::Renderer::Links#render when no item is selected renders items without the 'selected' class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:49:in `block (4 levels) in <module:Renderer>'

  23) SimpleNavigation::Renderer::Links#render when an item is selected renders the selected item with the 'selected' class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:57:in `block (4 levels) in <module:Renderer>'

  24) SimpleNavigation::Renderer::Links#render when a sub navigation item is selected renders the main parent as selected
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:78:in `block (4 levels) in <module:Renderer>'

  25) SimpleNavigation::Renderer::Links#render when a sub navigation item is selected doesn't render the nested item's link
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/links_spec.rb:9:in `block (3 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/links_spec.rb:82:in `block (4 levels) in <module:Renderer>'

  26) SimpleNavigation::Renderer::Breadcrumbs#render sets the right html id on the rendered 'div' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:20:in `block (3 levels) in <module:Renderer>'

  27) SimpleNavigation::Renderer::Breadcrumbs#render renders a 'div' tag for the navigation
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:16:in `block (3 levels) in <module:Renderer>'

  28) SimpleNavigation::Renderer::Breadcrumbs#render sets the right html classes on the rendered 'div' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:24:in `block (3 levels) in <module:Renderer>'

  29) SimpleNavigation::Renderer::Breadcrumbs#render when no item is selected doesn't render any 'a' tag in the 'div' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:29:in `block (4 levels) in <module:Renderer>'

  30) SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected renders all items as links
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:100:in `block (4 levels) in <module:Renderer>'

  31) SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected when the :static_leaf option is true renders the last item as simple text
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:111:in `block (5 levels) in <module:Renderer>'

  32) SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected when the :static_leaf option is true renders the items as links
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:107:in `block (5 levels) in <module:Renderer>'

  33) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected remders the 'a' tag without any html id
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:41:in `block (4 levels) in <module:Renderer>'

  34) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected renders the 'a' tag without any html class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:45:in `block (4 levels) in <module:Renderer>'

  35) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected renders the selected 'a' tag
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:37:in `block (4 levels) in <module:Renderer>'

  36) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true renders the 'a' tag with the selected class
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:52:in `block (5 levels) in <module:Renderer>'

  37) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true and the item has an explicitly set id renders the 'a' tag with an html id
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:65:in `block (6 levels) in <module:Renderer>'

  38) SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true and the item hasn't any id explicitly set renders the 'a' tag without any html id
      Failure/Error: let(:output) { HTML::Document.new(raw_output).root }

      NameError:
        uninitialized constant SimpleNavigation::Renderer::HTML
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:8:in `block (2 levels) in <module:Renderer>'
      # ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:57:in `block (6 levels) in <module:Renderer>'

Finished in 0.45511 seconds (files took 1.06 seconds to load)
385 examples, 38 failures

Failed examples:

rspec ./spec/simple_navigation/renderer/list_spec.rb:23 # SimpleNavigation::Renderer::List#render sets the right html classes on the rendered 'ul' tag
rspec ./spec/simple_navigation/renderer/list_spec.rb:15 # SimpleNavigation::Renderer::List#render renders an 'ul' tag for the navigation
rspec ./spec/simple_navigation/renderer/list_spec.rb:19 # SimpleNavigation::Renderer::List#render sets the right html id on the rendered 'ul' tag
rspec ./spec/simple_navigation/renderer/list_spec.rb:52 # SimpleNavigation::Renderer::List#render when an item is selected renders the item's 'li' tag with its id and selected classes
rspec ./spec/simple_navigation/renderer/list_spec.rb:56 # SimpleNavigation::Renderer::List#render when an item is selected renders the item's 'a' tag with the selected classes
rspec ./spec/simple_navigation/renderer/list_spec.rb:28 # SimpleNavigation::Renderer::List#render when an item has no specified id renders the item's 'li' tag with the item's stingified key as id
rspec ./spec/simple_navigation/renderer/list_spec.rb:34 # SimpleNavigation::Renderer::List#render when an item has a specified id renders the item's 'li' tag with the specified id
rspec ./spec/simple_navigation/renderer/list_spec.rb:68 # SimpleNavigation::Renderer::List#render when the :ordered option is true sets the right html id on the rendered 'ol' tag
rspec ./spec/simple_navigation/renderer/list_spec.rb:72 # SimpleNavigation::Renderer::List#render when the :ordered option is true sets the right html classes on the rendered 'ol' tag
rspec ./spec/simple_navigation/renderer/list_spec.rb:64 # SimpleNavigation::Renderer::List#render when the :ordered option is true renders an 'ol' tag for the navigation
rspec ./spec/simple_navigation/renderer/list_spec.rb:44 # SimpleNavigation::Renderer::List#render when no item is selected renders each item as 'a' tag without any selected class
rspec ./spec/simple_navigation/renderer/list_spec.rb:40 # SimpleNavigation::Renderer::List#render when no item is selected renders each item as 'li' tag without any selected class
rspec ./spec/simple_navigation/renderer/list_spec.rb:89 # SimpleNavigation::Renderer::List#render when a sub navigation item is selected renders the selected nested item's link as selected
rspec ./spec/simple_navigation/renderer/list_spec.rb:85 # SimpleNavigation::Renderer::List#render when a sub navigation item is selected renders the parent items as selected
rspec ./spec/simple_navigation/renderer/links_spec.rb:23 # SimpleNavigation::Renderer::Links#render sets the right html classes on the rendered 'div' tag
rspec ./spec/simple_navigation/renderer/links_spec.rb:19 # SimpleNavigation::Renderer::Links#render sets the right html id on the rendered 'div' tag
rspec ./spec/simple_navigation/renderer/links_spec.rb:15 # SimpleNavigation::Renderer::Links#render renders a 'div' tag for the navigation
rspec ./spec/simple_navigation/renderer/links_spec.rb:31 # SimpleNavigation::Renderer::Links#render renders the 'a' tags with the corresponding item's :html_options
rspec ./spec/simple_navigation/renderer/links_spec.rb:27 # SimpleNavigation::Renderer::Links#render renders an 'a' tag for each item
rspec ./spec/simple_navigation/renderer/links_spec.rb:42 # SimpleNavigation::Renderer::Links#render when an item has no specified id uses a default id by stringifying the item's key
rspec ./spec/simple_navigation/renderer/links_spec.rb:36 # SimpleNavigation::Renderer::Links#render when an item has a specified id renders the 'a' tags with the specified id
rspec ./spec/simple_navigation/renderer/links_spec.rb:48 # SimpleNavigation::Renderer::Links#render when no item is selected renders items without the 'selected' class
rspec ./spec/simple_navigation/renderer/links_spec.rb:56 # SimpleNavigation::Renderer::Links#render when an item is selected renders the selected item with the 'selected' class
rspec ./spec/simple_navigation/renderer/links_spec.rb:77 # SimpleNavigation::Renderer::Links#render when a sub navigation item is selected renders the main parent as selected
rspec ./spec/simple_navigation/renderer/links_spec.rb:81 # SimpleNavigation::Renderer::Links#render when a sub navigation item is selected doesn't render the nested item's link
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:19 # SimpleNavigation::Renderer::Breadcrumbs#render sets the right html id on the rendered 'div' tag
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:15 # SimpleNavigation::Renderer::Breadcrumbs#render renders a 'div' tag for the navigation
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:23 # SimpleNavigation::Renderer::Breadcrumbs#render sets the right html classes on the rendered 'div' tag
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:28 # SimpleNavigation::Renderer::Breadcrumbs#render when no item is selected doesn't render any 'a' tag in the 'div' tag
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:99 # SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected renders all items as links
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:110 # SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected when the :static_leaf option is true renders the last item as simple text
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:106 # SimpleNavigation::Renderer::Breadcrumbs#render when a sub navigation item is selected when the :static_leaf option is true renders the items as links
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:40 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected remders the 'a' tag without any html id
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:44 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected renders the 'a' tag without any html class
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:36 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected renders the selected 'a' tag
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:51 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true renders the 'a' tag with the selected class
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:64 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true and the item has an explicitly set id renders the 'a' tag with an html id
rspec ./spec/simple_navigation/renderer/breadcrumbs_spec.rb:56 # SimpleNavigation::Renderer::Breadcrumbs#render when an item is selected and the :allow_classes_and_ids option is true and the item hasn't any id explicitly set renders the 'a' tag without any html id
```

**Comment by andi** [comment]
thanks for the info. It would be great if you could submit a PR
